### ISSUE TITLE
Unhandled Promise Rejection Warning

### ISSUE THREAD

**Issue by rehanratnaweera** [TannerGabriel/discord-bot#10]
How can I fix this?
```
TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received type object
    at validateString (internal/validators.js:112:11)
    at normalizeSpawnArguments (child_process.js:398:3)
    at Object.spawn (child_process.js:534:16)
    at new FfmpegProcess (C:\Users\rehanratnaweera\node_modules\prism-media\src\transcoders\ffmpeg\FfmpegProcess.js:14:33)
    at FfmpegTranscoder.transcode (C:\Users\rehanratnaweera\node_modules\prism-media\src\transcoders\ffmpeg\Ffmpeg.js:34:18)
    at MediaTranscoder.transcode (C:\Users\rehanratnaweera\node_modules\prism-media\src\transcoders\MediaTranscoder.js:27:31)
    at Prism.transcode (C:\Users\rehanratnaweera\node_modules\prism-media\src\Prism.js:13:28)
    at AudioPlayer.playUnknownStream (C:\Users\rehanratnaweera\node_modules\discord.js\src\client\voice\player\AudioPlayer.js:97:35)
    at VoiceConnection.playStream (C:\Users\rehanratnaweera\node_modules\discord.js\src\client\voice\VoiceConnection.js:478:24)
    at Object.play (C:\Users\rehanratnaweera\Desktop\mybot\commands\play.js:78:8) {
  code: 'ERR_INVALID_ARG_TYPE'
}
(node:9000) UnhandledPromiseRejectionWarning: DiscordAPIError: Cannot send an empty message
    at C:\Users\rehanratnaweera\node_modules\discord.js\src\client\rest\RequestHandlers\Sequential.js:85:15
    at C:\Users\rehanratnaweera\node_modules\snekfetch\src\index.js:215:21
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:9000) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:9000) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by TannerGabriel** [comment]
Could you provide more information like when you are getting this error and if you have changed anything in the code.

If you are getting the error when using a command please provide the command and the specific arguments you are using.

**Comment by SatanFreeman** [comment]
m8, update your ffmpeg 
or install it globally using
npm i -g ffmpeg-static
