### ISSUE TITLE
Error [TOKEN_INVALID]: An invalid token was provided.

### ISSUE THREAD

**Issue by Phantommmmm** [TannerGabriel/discord-bot#105]
Although I have provided a valid token in the config.js file, I still get this error. I have tried to regenerate the token several times.

Steps to reproduce:

- Install requiered programs
- Run npm install
- Run node index.js

```
/home/ubuntu/discord-bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:123
    const invalidToken = new Error(WSCodes[4004]);
                         ^

Error [TOKEN_INVALID]: An invalid token was provided.
    at WebSocketManager.connect (/home/ubuntu/discord-bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:123:26)
    at module.exports.login (/home/ubuntu/discord-bot/node_modules/discord.js/src/client/Client.js:245:21)
    at Object.<anonymous> (/home/ubuntu/discord-bot/index.js:93:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47 {
  [Symbol(code)]: 'TOKEN_INVALID'

```

**Comment by TannerGabriel** [comment]
I have only ever seen that error message if an invalid token was passed to the discord.js library. Please make sure that you copy the correct token from the dashboard. You can take a look at [this guide](https://gabrieltanner.org/blog/dicord-music-bot#setting-up-a-discord-bot) if you need help.

**Comment by hotsu0p** [comment]
i am also getting this error.
