### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by kingisawesome** [TannerGabriel/discord-bot#123]
I am trying to run this bot on repl.it since I want it on for 24/7 (already have the hacker plan), but the problem is, every time I run the `Node index.js `command I receive this error
![7773B94F-B429-4C7B-B9B1-6CE5EF3B13F5](https://user-images.githubusercontent.com/70557332/134336285-bc2c3b92-be0a-4163-ac85-70a1a0ef05e1.jpeg)

Is there anything I can do to fix this? I have also heard that repl.it does not support FFmpeg so that might be the issue but I am not too sure.

**Comment by willm132** [comment]
I host mine on Heroku, it's free and works great.

**Comment by smclean117** [comment]
Hosting on AWS ubuntu t2.micro, free for first 12 months from account opening, got it working nicely.

I had this unexpected token error, updating node to v16.9.1 fixed it.

**Comment by kingisawesome** [comment]
> I host mine on Heroku, it's free and works great.
Hi, I initially going to host it in heroku, but I get extremely confused on how. Would you mind giving me some instructions?

**Comment by kingisawesome** [comment]
> I host mine on Heroku, it's free and works great.

@willm132 Hi, I initially going to host it in heroku, but I get extremely confused on how. Would you mind giving me some instructions?

**Comment by kingisawesome** [comment]
Update:

So I successfully updated node.js to the latest version but I encountered another problem when typing the `Node Index.js` command

![896AA7DE-1AD6-4168-962F-1710C66446F2](https://user-images.githubusercontent.com/70557332/134357446-a7e4c2e9-23ed-4c05-9837-69ae896ef843.jpeg)

Any solution to this?

**Comment by TannerGabriel** [comment]
Are you in the correct directory? It seems that you are executing the command in a directory that does not contain the `index.js` file.

**Comment by kingisawesome** [comment]
> Are you in the correct directory? It seems that you are executing the command in a directory that does not contain the `index.js` file.

 @TannerGabriel Sorry Yes, but now that I used the `cd discord-bot` command in which the index.js file lies, I still receive the same unexpected token error, even though I updated everything.
![8FDEA2E8-C63D-47C4-925E-5CA3F9E0CEB0](https://user-images.githubusercontent.com/70557332/134689382-2fa62573-a528-46a1-9489-03f71d6242b8.jpeg)

**Comment by TannerGabriel** [comment]
@kingisawesome No, it seems that you don't have the correct discord bot token inside of the `config.json` file. Please take a look at [this guide](https://gabrieltanner.org/blog/dicord-music-bot#setting-up-a-discord-bot) for more information.

**Comment by kingisawesome** [comment]
@TannerGabriel I have done that part correctly, actually it works well on my machine and I have followed the same steps on replit but in replit I keep receiving this error:
```
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by shinyduck** [comment]
did you update your node.js to v16.6.0+ because discord.js v13 won't work on node.js v12.16.1 that replit uses.

**Comment by kingisawesome** [comment]
Alright the problem is solved, so you see it is a little tricky to update node.js in replit but here is the solution: Go to the shell and type this:
`npm init -y && npm i --save-dev node@16 && npm config set prefix=$(pwd)/node_modules/node && export PATH=$(pwd)/node_modules/node/bin:$PATH
`
Then it would work perfectly
