### ISSUE TITLE
Discord.js V12 Error

### ISSUE THREAD

**Issue by MrPvTDagger** [TannerGabriel/discord-bot#15]
**Describe the bug**
Error when executing index.js

```
@localhost:~/discord-bot$ node index.js
/discord-bot/node_modules/discord.js/src/client/Client.js:40
    } catch {
            ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/discord-bot/node_modules/discord.js/src/index.js:8:11)

@localhost:~/discord_bot$ npm -v
3.5.2
@localhost:~/discord_bot$ node -v
v8.10.0
```

Tried it with a older version and it works fine.

**Comment by MrPvTDagger** [comment]
I'm a bit special found this https://github.com/discordjs/discord.js/issues/1386 fixed the issue.

**Make sure to use node >12.* **
