### ISSUE TITLE
Not playing music

### ISSUE THREAD

**Issue by willm132** [TannerGabriel/discord-bot#154]
/play query: super gremlin
** bot joins channel **
 ⏱ | Loading your track...
🎶 | Track Kodak Black - Super Gremlin [Official Music Video] queued!
** song never plays and gives this error in cmd **
```
DiscordAPIError: Unknown interaction
    at RequestHandler.execute (C:\Users\willm\Desktop\Other\GitHub\FADA-Bot\node_modules\discord.js\src\rest\RequestHandler.js:298:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\willm\Desktop\Other\GitHub\FADA-Bot\node_modules\discord.js\src\rest\RequestHandler.js:50:14)
    at async CommandInteraction.deferReply (C:\Users\willm\Desktop\Other\GitHub\FADA-Bot\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:58:5)
    at async Object.execute (C:\Users\willm\Desktop\Other\GitHub\FADA-Bot\commands\play.js:34:7) {
  method: 'post',
  path: '/interactions/928460589028745226/aW50ZXJhY3Rpb246OTI4NDYwNTg5MDI4NzQ1MjI2Ok4xUW5NeXN2Z0FnSG52bXd2cnZPSHYxbUZrSG5tMWtUaUJCRGtDUVhVYWxKbjRJMzBkZ2dacWFlcUR1aWNwV2lIZzJYVFB2bzhpekxncEtpbHdiUXU1S2lWZUllVko4YXZyejlIaEJrZXd4Z1RXYnp2bk51bTVTNEZJRHRLNEx5/callback',
  code: 10062,
  httpStatus: 404,
  requestData: { json: { type: 5, data: [Object] }, files: [] }
}
```

**Comment by TannerGabriel** [comment]
Did you use the `!deploy` command to create the interactions?
