### ISSUE TITLE
discordJs dependency outdated

### ISSUE THREAD

**Issue by Pim112** [TannerGabriel/discord-bot#179]
**Describe the bug**

cannot play song

**To Reproduce**

start application, !deploy and /play a yt link

**Expected behavior**

playing a youtube song

**Screenshots (optional)**

the reason it broke is because discord updated their package, see:
https://discordjs.guide/additional-info/changes-in-v14.html#before-you-start

when trying to play the following error pops in console:

```  'ban' => {
    name: 'ban',
    description: 'Ban a player',
    options: [ [Object] ],
    execute: [Function: execute]
  },
  'help' => {
    name: 'help',
    description: 'List all available commands.',
    execute: [Function: execute]
  },
  'loop' => {
    name: 'loop',
    description: 'Sets loop mode',
    options: [ [Object] ],
    execute: [AsyncFunction: execute]
  },
  'move' => {
    name: 'move',
    description: 'move song position in the queue!',
    options: [ [Object], [Object] ],
    execute: [AsyncFunction: execute]
  },
  'nowplaying' => {
    name: 'nowplaying',
    description: 'Get the song that is currently playing.',
    execute: [AsyncFunction: execute]
  },
  'pause' => {
    name: 'pause',
    description: 'Pause current song!',
    execute: [AsyncFunction: execute]
  },
  'play' => {
    name: 'play',
    description: 'Play a song in your channel!',
    options: [ [Object] ],
    execute: [AsyncFunction: execute]
  },
  'playtop' => {
    name: 'playtop',
    description: 'Play a song before the next in your channel!',
    options: [ [Object] ],
    execute: [AsyncFunction: execute]
  },
  'purge' => {
    name: 'purge',
    description: 'Delete the last messages in all chats.',
    options: [ [Object] ],
    execute: [AsyncFunction: execute]
  },
  'queue' => {
    name: 'queue',
    description: 'View the queue of current songs!',
    execute: [AsyncFunction: execute]
  },
  'remove' => {
    name: 'remove',
    description: 'remove a song from the queue!',
    options: [ [Object] ],
    execute: [AsyncFunction: execute]
  },
  'resume' => {
    name: 'resume',
    description: 'Resume current song!',
    execute: [AsyncFunction: execute]
  },
  'shuffle' => {
    name: 'shuffle',
    description: 'shuffle the queue!',
    execute: [AsyncFunction: execute]
  },
  'skip' => {
    name: 'skip',
    description: 'Skip a song!',
    execute: [AsyncFunction: execute]
  },
  'stop' => {
    name: 'stop',
    description: 'Stop all songs in the queue!',
    execute: [AsyncFunction: execute]
  },
  'swap' => {
    name: 'swap',
    description: 'swap song positions in the queue!',
    options: [ [Object], [Object] ],
    execute: [AsyncFunction: execute]
  },
  'userinfo' => {
    name: 'userinfo',
    description: 'Get information about a user.',
    options: [ [Object] ],
    execute: [Function: execute]
  },
  'volume' => {
    name: 'volume',
    description: 'Change the volume!',
    options: [ [Object] ],
    execute: [AsyncFunction: execute]
  }
}
Ready!
DiscordAPIError: Invalid Webhook Token
    at RequestHandler.execute (C:\Users\pim_b\IdeaProjects\discord_bot\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\pim_b\IdeaProjects\discord_bot\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async InteractionWebhook.send (C:\Users\pim_b\IdeaProjects\discord_bot\node_modules\discord.js\src\structures\Webhook.js:196:15)
    at async Object.execute (C:\Users\pim_b\IdeaProjects\discord_bot\commands\play.js:65:7) {
  method: 'post',
  path: '/webhooks/266301504460161024/aW50ZXJhY3Rpb246MTAwMDAyMzc0Njc2NzIzMzAzNDpsTnN3R3h5T29ESm1Jd0NPSGx4cmswV05jaVU2bldKM3hhOVBWbnlKUlVBWGFuMlp5RDRCcHFsMWE2SGNNSkJoQVVSbnZyQU4xTFJXZHBvSWw4SlpSOHFLVWhjMUxVc2lHUGVlYUtZ
OWxlYzZuNU5EWHJZWWRrcUhDVWpsOXFCMQ?wait=true',
  code: 50027,
  httpStatus: 401,
  requestData: {
    json: {
      content: '⏱ | Loading your track...',
      tts: false,
      nonce: undefined,
      embeds: undefined,
      components: undefined,
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: undefined,
      message_reference: undefined,
      attachments: undefined,
      sticker_ids: undefined
    },
    files: []
  }
}
C:\Users\pim_b\IdeaProjects\discord_bot\node_modules\discord.js\src\rest\RequestHandler.js:350
      throw new DiscordAPIError(data, res.status, request);
            ^

DiscordAPIError: Invalid Webhook Token
    at RequestHandler.execute (C:\Users\pim_b\IdeaProjects\discord_bot\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\pim_b\IdeaProjects\discord_bot\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async InteractionWebhook.send (C:\Users\pim_b\IdeaProjects\discord_bot\node_modules\discord.js\src\structures\Webhook.js:196:15) {
  method: 'post',
  path: '/webhooks/266301504460161024/aW50ZXJhY3Rpb246MTAwMDAyMzc0Njc2NzIzMzAzNDpsTnN3R3h5T29ESm1Jd0NPSGx4cmswV05jaVU2bldKM3hhOVBWbnlKUlVBWGFuMlp5RDRCcHFsMWE2SGNNSkJoQVVSbnZyQU4xTFJXZHBvSWw4SlpSOHFLVWhjMUxVc2lHUGVlYUtZ
OWxlYzZuNU5EWHJZWWRrcUhDVWpsOXFCMQ?wait=true',
  code: 50027,
  httpStatus: 401,
    json: {
      tts: false,
      nonce: undefined,
      embeds: undefined,
      components: undefined,
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: undefined,
      message_reference: undefined,
      attachments: undefined,
      sticker_ids: undefined
    },
    files: []
  }
}

```

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - CPU architecture: [e.g. x86]

both rpi4 (ARM64) and windows10 x64

**Dependency versions:**
 - Nodejs version: [e.g. 10]
 - YTDL-core version: [e.g. 4.4.5]

node v16.14.2
ytdl-core: "^4.11.0"

**Additional context (optional)**

**Comment by blakewon** [comment]
bump

**Comment by jaeblaze1989** [comment]
bump

**Comment by TannerGabriel** [comment]
Updating to the new `discord.js` and `discord-player` version needs a couple of changes in the codebase, and I'm currently really short on time. You are welcome to update the dependencies yourself and submit a PR if possible. Else you will have to wait a bit longer until I find the time to update it.

**Comment by nukinuka** [comment]
> Updating to the new `discord.js` and `discord-player` version needs a couple of changes in the codebase, and I'm currently really short on time. You are welcome to update the dependencies yourself and submit a PR if possible. Else you will have to wait a bit longer until I find the time to update it.

Same issue, looking forward to the update. Thank you for your hard work Tanner
