### ISSUE TITLE
Youtube Links not working

### ISSUE THREAD

**Issue by TlMcook** [TannerGabriel/discord-bot#226]
Additionally it seems as though youtube links have stopped working all together.
![image](https://user-images.githubusercontent.com/43119444/235032023-eaaf9342-b803-4380-81ce-75ad99493ce7.png)
This time is seems a complete reinstall works and fixes the original issue, however the problem with it being unable to play youtube links still stands.

_Originally posted by @TlMcook in https://github.com/TannerGabriel/discord-bot/issues/225#issuecomment-1526848908_

**Comment by TlMcook** [comment]
Describe the bug
The Bot will not play music from youtube links.

To Reproduce
Steps to reproduce the behavior:

/play a youtube link
bug happens

Expected behavior
It is expected play the link.

Desktop (please complete the following information):

OS: Windows 11
CPU architecture: x64
Dependency versions:

Nodejs version: v18.12.1
YTDL-core version: v4.11.2

**Comment by TlMcook** [comment]
I am also apparently a buffoon and the reinstall only fixes the original issue _temporarily_

**Comment by TlMcook** [comment]
All problems can be fixed by following the commits in renovate[bot]'s branches for the discord-bot :)

**Comment by TlMcook** [comment]
Nevermind it played one song and then stopped working ,-,

**Comment by TannerGabriel** [comment]
I currently have little time. I will try to look at the issue at the end of next week.

**Comment by victoralcan** [comment]
I'm having the same issue. I can't play any music from youtube. I've tried to run it on my local computer and a server on digital ocean, both with Ubuntu 22.04

**Comment by TlMcook** [comment]
I have finally been able to get an error log:
`TypeError: Cannot read properties of undefined (reading 'execute')
    at module.exports.<anonymous> (C:\Users\minor\discord-bot\index.js:111:15)
    at module.exports.emit (node:events:511:28)
    at InteractionCreateAction.handle (C:\Users\minor\discord-bot\node_modules\discord.js\src\client\actions\InteractionCreate.js:97:12)
    at module.exports [as INTERACTION_CREATE] (C:\Users\minor\discord-bot\node_modules\discord.js\src\client\websocket\handlers\INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (C:\Users\minor\discord-bot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:352:31)
    at WebSocketShard.onPacket (C:\Users\minor\discord-bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:489:22)
    at WebSocketShard.onMessage (C:\Users\minor\discord-bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:328:10)
    at callListener (C:\Users\minor\discord-bot\node_modules\ws\lib\event-target.js:290:14)
    at WebSocket.onMessage (C:\Users\minor\discord-bot\node_modules\ws\lib\event-target.js:209:9)
    at WebSocket.emit (node:events:511:28)
C:\Users\minor\discord-bot\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:184
    if (!this.deferred && !this.replied) return Promise.reject(new DiscordjsError(ErrorCodes.InteractionNotReplied));
                                                               ^

Error [InteractionNotReplied]: The reply to this interaction has not been sent or deferred.
    at ChatInputCommandInteraction.followUp (C:\Users\minor\discord-bot\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:184:64)
    at module.exports.<anonymous> (C:\Users\minor\discord-bot\index.js:115:17)
    at module.exports.emit (node:events:511:28)
    at InteractionCreateAction.handle (C:\Users\minor\discord-bot\node_modules\discord.js\src\client\actions\InteractionCreate.js:97:12)
    at module.exports [as INTERACTION_CREATE] (C:\Users\minor\discord-bot\node_modules\discord.js\src\client\websocket\handlers\INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (C:\Users\minor\discord-bot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:352:31)
    at WebSocketShard.onPacket (C:\Users\minor\discord-bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:489:22)
    at WebSocketShard.onMessage (C:\Users\minor\discord-bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:328:10)
    at callListener (C:\Users\minor\discord-bot\node_modules\ws\lib\event-target.js:290:14)
    at WebSocket.onMessage (C:\Users\minor\discord-bot\node_modules\ws\lib\event-target.js:209:9) {
  code: 'InteractionNotReplied'
}

Node.js v20.0.0`

**Comment by TlMcook** [comment]
adding:
`try {
        // do some crazy stuff
    } catch (e) {
        console.error(e, e.stack);
    }`
to line 76 of play.js fixes the problem _for some _reason._
