### ISSUE TITLE
What FFmpeg do I install and setup?

### ISSUE THREAD

**Issue by Mystik01** [TannerGabriel/discord-bot#31]
I downloaded the version already set on [this link,](https://ffmpeg.zeranoe.com/builds/) I don't think it's working though... Any idea how?

This is my error when i try to play music:
```
``info.title` will be removed in a near future release, use `info.videoDetails.title` instead.
`info.video_url` will be removed in a near future release, use `info.videoDetails.video_url` instead.
Error: FFmpeg/avconv not found!
    at Function.getInfo (C:\Users\logan\Documents\GitHub\discord-bot\node_modules\prism-media\src\core\FFmpeg.js:130:11)
    at Function.create (C:\Users\logan\Documents\GitHub\discord-bot\node_modules\prism-media\src\core\FFmpeg.js:143:38)
    at new FFmpeg (C:\Users\logan\Documents\GitHub\discord-bot\node_modules\prism-media\src\core\FFmpeg.js:44:27)
    at AudioPlayer.playUnknown (C:\Users\logan\Documents\GitHub\discord-bot\node_modules\discord.js\src\client\voice\player\BasePlayer.js:47:20)
    at VoiceConnection.play (C:\Users\logan\Documents\GitHub\discord-bot\node_modules\discord.js\src\client\voice\util\PlayInterface.js:71:28)
    at Object.play (C:\Users\logan\Documents\GitHub\discord-bot\commands\play.js:77:8)
    at Object.execute (C:\Users\logan\Documents\GitHub\discord-bot\commands\play.js:47:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:7344) UnhandledPromiseRejectionWarning: DiscordAPIError: Cannot send an empty message
    at RequestHandler.execute (C:\Users\logan\Documents\GitHub\discord-bot\node_modules\discord.js\src\rest\RequestHandler.js:170:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:7344) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7344) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
```

Help appreciated thanks!

**Comment by TannerGabriel** [comment]
I run the application using Docker, but every installation using the [official website](https://www.ffmpeg.org/download.html) should be fine.

You can try uninstalling your current version and then installing the newest version using the link I send you above.
