### ISSUE TITLE
when i start it every thing runs fine but no sound but it shows sound should be playing 

### ISSUE THREAD

**Issue by YTFlashplayz** [TannerGabriel/discord-bot#32]

**Comment by Mima4** [comment]
I have same problem

**Comment by TannerGabriel** [comment]
I'm sorry to hear that, but could you provide more information like your setup and error message so I could help you fix the issue.

Also, take a look at the following #29, which is very similar to yours and try the solution I suggest there.

**Comment by Mima4** [comment]
i write !play and URL and its write this to me in visual studio:
Error: FFmpeg/avconv not found!
    at Function.getInfo (C:\Users\Pc\Desktop\musicbot\node_modules\prism-media\src\core\FFmpeg.js:130:11)
    at Function.create (C:\Users\Pc\Desktop\musicbot\node_modules\prism-media\src\core\FFmpeg.js:143:38)
    at new FFmpeg (C:\Users\Pc\Desktop\musicbot\node_modules\prism-media\src\core\FFmpeg.js:44:27)
    at AudioPlayer.playUnknown (C:\Users\Pc\Desktop\musicbot\node_modules\discord.js\src\client\voice\player\BasePlayer.js:47:20)
    at VoiceConnection.play (C:\Users\Pc\Desktop\musicbot\node_modules\discord.js\src\client\voice\util\PlayInterface.js:71:28)
    at play (C:\Users\Pc\Desktop\musicbot\index.js:119:4)
    at execute (C:\Users\Pc\Desktop\musicbot\index.js:79:7)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:14924) UnhandledPromiseRejectionWarning: DiscordAPIError: Cannot send an empty message
    at RequestHandler.execute (C:\Users\Pc\Desktop\musicbot\node_modules\discord.js\src\rest\RequestHandler.js:170:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14924) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:14924) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by TannerGabriel** [comment]
Make sure that you have FFMPEG installed on your local system. Here is a link to the [official download](https://www.ffmpeg.org/).

**Comment by Mima4** [comment]
I need to install that in file where bot is or just on my PC?

**Comment by D3ord3NidAm** [comment]
I got this same error. 
run `npm i ffmpeg-static --save`  it should work

**Comment by TannerGabriel** [comment]
Yes you need to install it on the PC that is running `index.js`. If it is still not working I would recommend running the application using the provided Dockerfile. The instructions to do so can be found in the `README.md` file.
