### ISSUE TITLE
Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by sketch-prime** [TannerGabriel/discord-bot#37]
I keep getting this error when ever I try and run the !play command. I am pretty new to programming and stuff and I just cannot figure this out. 

here is the error message in the console:
TypeError: Cannot read property 'get' of undefined
    at Object.execute (C:\Users\sketc\Desktop\SATAN BOT\commands\play.js:13:48)
    at Client.<anonymous> (C:\Users\sketc\Desktop\SATAN BOT\index.js:73:34)
    at Client.emit (events.js:322:22)
    at MessageCreateAction.handle (C:\Users\sketc\Desktop\SATAN BOT\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\sketc\Desktop\SATAN BOT\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\sketc\Desktop\SATAN BOT\node_modules\discord.js\src\client\websocket\WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (C:\Users\sketc\Desktop\SATAN BOT\node_modules\discord.js\src\client\websocket\WebSocketShard.js:436:22)
    at WebSocketShard.onMessage (C:\Users\sketc\Desktop\SATAN BOT\node_modules\discord.js\src\client\websocket\WebSocketShard.js:293:10)
    at WebSocket.onMessage (C:\Users\sketc\Desktop\SATAN BOT\node_modules\ws\lib\event-target.js:125:16)
    at WebSocket.emit (events.js:310:20)

**Comment by sketch-prime** [comment]
oops didnt see that new thread for earlier. that one fixed the original problem
