### ISSUE TITLE
play command doesnt work. Says Video Unavailable

### ISSUE THREAD

**Issue by RayZ3R0** [TannerGabriel/discord-bot#40]
Play command isnt working. when I give a link it says Video Unavailable
I havent changed the prefix.

it gives this error ._.

`Error: Video unavailable
    at Object.exports.playError (D:\OTHERS\bot3\node_modules\ytdl-core\lib\util.
js:444:12)
    at exports.getBasicInfo (D:\OTHERS\bot3\node_modules\ytdl-core\lib\info.js:7
7:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Map.getOrSet (D:\OTHERS\bot3\node_modules\ytdl-core\lib\cache.js:24
:19)
    at async exports.getInfo (D:\OTHERS\bot3\node_modules\ytdl-core\lib\info.js:
215:14)
    at async Map.getOrSet (D:\OTHERS\bot3\node_modules\ytdl-core\lib\cache.js:24
:19)
    at async Object.execute (D:\OTHERS\bot3\commands\play.js:24:24)
`

Please Help.

**Comment by TannerGabriel** [comment]
Please try updating the `ytdl-core` dependency and tell me if it works.

```bash
npm install ytdl-core@latest
```

**Comment by RayZ3R0** [comment]
Still not working :/
getting the same error as before. @TannerGabriel

**Comment by RayZ3R0** [comment]
Thanks : D

It worked with VPN
