### ISSUE TITLE
DiscordAPIError when deleting message after music queue ends

### ISSUE THREAD

**Issue by SugarD-x** [TannerGabriel/discord-bot#43]
**Describe the bug**
When the music queue ends, the bot attempts to delete its messages, however instead triggers the following DiscordAPIError:
`DiscordAPIError: Unknown Message
    at RequestHandler.execute (\node_modules\discord.js\src\rest\RequestHandler.js:170:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  name: 'DiscordAPIError',
  message: 'Unknown Message',
  method: 'delete',
  path: '/channels/ID-PLACEHOLDER-HERE/messages/ID-PLACEHOLDER-HERE/reactions',
  code: 10008,
  httpStatus: 404
}`

**To Reproduce**
1. Play song using the music functions.
2. When the song ends, the bot exits the voice channel and states the music queue ended.
3. Error appears in console, and no messages are deleted.

**Expected behavior**
No error should be presented, and a message should be deleted.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows Server 2016 Standard Edition x64
 - Browser [e.g. chrome, safari] Not applicable
 - Version [e.g. 22] Latest repository copy

**Additional context**
This appears to be related to the following code in "_\include\play.js_":
`    if (!song) {
      queue.channel.leave();
      message.client.queue.delete(message.guild.id);
      return queue.textChannel.send("🚫 Music queue ended.").catch(console.error);
    }`
My best guess is that the third line of this section of code is causing the Discord API to not understand the output, hence the error. Unfortunately I don't know Discord.js well enough to figure this one out.

**Comment by SugarD-x** [comment]
It seems updating the bot's dependencies to the latest versions of them available, (including updating package.json and package-lock.json), fixed this. I'm not sure which dependency exactly was at fault.
