### ISSUE TITLE
Error with play command

### ISSUE THREAD

**Issue by joeljosephwebdev** [TannerGabriel/discord-bot#52]
**Describe the bug**
When I try to play a song using the bot I receive the following error; "Could not find player config"

**To Reproduce**
1. I cloned the repo
2. installed the dependencies
3. added my token to config 
4. and started the app with docker

**Expected behavior**
I expected the bot to join the voice channel and play music

**Screenshots**
![could not find player config](https://user-images.githubusercontent.com/70778169/100556700-8002d400-327a-11eb-9569-df1a92ce5d88.PNG)

**Copy of the Error from CLI**
Error: Could not find player config
at exports.getBasicInfo (/usr/src/app/node_modules/ytdl-core/lib/info.js:59:13)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async Object.exports.<computed> [as getBasicInfo] (/usr/src/app/node_modules/ytdl-core/lib/info.js:298:18)
at async exports.getFullInfo (/usr/src/app/node_modules/ytdl-core/lib/info.js:184:14)
at async Function.exports.<computed> [as getInfo] (/usr/src/app/node_modules/ytdl-core/lib/info.js:298:18)
at async Object.execute (/usr/src/app/commands/play.js:24:24)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
I confirmed I have the latest version of ytdl-core installed.

**Comment by joeljosephwebdev** [comment]
Maybe I made a mistake starting it with Docker. 
I started it with node instead and it worked with no errors, so I'll just chalk this one up to me being a scrub.
