### ISSUE TITLE
Can't play

### ISSUE THREAD

**Issue by ImASadBoy** [TannerGabriel/discord-bot#63]
**Describe the bug**
Every time i use the !play command the bot says "No video id found: NAME"
and the console prints this: 
`
Error: No video id found: hello
    at Object.exports.getVideoID (/discord-bot/node_modules/ytdl-core/lib/url-utils.js:66:11)
    at Function.exports.<computed> [as getInfo] (/discord-bot/node_modules/ytdl-core/lib/info.js:470:29)
    at Object.execute (/discord-bot/commands/play.js:24:35)
    at module.exports.<anonymous> (/discord-bot/index.js:45:12)
    at module.exports.emit (events.js:314:20)
    at MessageCreateAction.handle (/discord-bot/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/discord-bot/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/discord-bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/discord-bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/discord-bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
`
So i tried to run `npm install ytdl-core@latest` and it prints:
`+ ytdl-core@4.4.5
updated 1 package and audited 94 packages in 2.377s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
`

**Expected behavior**
Playing a song

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Additional context**
every other command work

**Comment by ImASadBoy** [comment]
I just found out i need to provide a link and not words. Sorry
