### ISSUE TITLE
Hi I have. issue with execute

### ISSUE THREAD

**Issue by VASAPOL** [TannerGabriel/discord-bot#77]
- OS: macOS 11.5.1/Window 10
 - CPU architecture: x86

TypeError: Cannot read property 'execute' of undefined
    at module.exports.<anonymous> (/Users/.../Downloads/discord-bot-master/index.js:45:12)
    at module.exports.emit (node:events:394:28)
    at MessageCreateAction.handle (/Users/.../Downloads/discord-bot-master/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/Users/.../Downloads/discord-bot-master/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/Users/.../Downloads/discord-bot-master/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/Users/.../Downloads/discord-bot-master/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/Users/.../Downloads/discord-bot-master/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/Users/.../Downloads/discord-bot-master/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (node:events:394:28)
    at Receiver.receiverOnMessage (/Users/.../Downloads/discord-bot-master/node_modules/ws/lib/websocket.js:834:20)

**Comment by beeetooo** [comment]
Running it with docker works very smoothly btw 👍 not a single issue, just changing the config.json token and you are good to go @VASAPOL

**Comment by TannerGabriel** [comment]
I will close this issue since it should be fixed. If anyone still experiences such problems feel free to leave a comment here or reopen the issue.
