### ISSUE TITLE
abort controller is not defined

### ISSUE THREAD

**Issue by fliecs** [TannerGabriel/discord-bot#80]
when i try to run index.js i get referenceerror abortcontroller is not defined. running windows 11 22000.168
path D:\\discord-bot-master\node_modules\discord.js\src\rest\RequestHandler

**Comment by fliecs** [comment]
full error ^^^^^^^^

(node:6716) UnhandledPromiseRejectionWarning: ReferenceError: AbortController is not defined
    at RequestHandler.execute (C:\Users\willi\discord-bot\node_modules\discord.js\src\rest\RequestHandler.js:172:15)
    at RequestHandler.execute (C:\Users\willi\discord-bot\node_modules\discord.js\src\rest\RequestHandler.js:176:19)
    at RequestHandler.push (C:\Users\willi\discord-bot\node_modules\discord.js\src\rest\RequestHandler.js:50:25)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async WebSocketManager.connect (C:\Users\willi\discord-bot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:128:9)
    at async module.exports.login (C:\Users\willi\discord-bot\node_modules\discord.js\src\client\Client.js:245:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6716) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:6716) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
