### ISSUE TITLE
node index.js command fails to start bot ; results in syntax error (Unexpected token .)

### ISSUE THREAD

**Issue by Ao1Pointblank** [TannerGabriel/discord-bot#82]
**Describe the bug**
termial output:

me@macmini:~/discord-bot$ sudo node index.js 
/home/me/discord-bot/index.js:63
  if (!client.application?.owner) await client.application?.fetch();
                          ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**To Reproduce**
1. set up oauth and permissions in discord dev portal
2. install dependencies
3. run node index.js in bot folder

**Expected behavior**
the bot should probably give a message saying it is successfully launched?

**Desktop:**
 - OS: Linux Mint 20.2
 - CPU architecture: x86

**Dependency versions:**
 - Nodejs version: 10.19.0
 - YTDL-core version: 4.9.1
 
**Additional context (optional)**
I am new to making discord bots, having been forced to create my own due to the DMCA ban youtube enacted on discord music bots. it's running on a toaster 2010 macmini converted to Mint

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/TannerGabriel/discord-bot/issues?q=is%3Aissue)

**Comment by Ao1Pointblank** [comment]
I tried running it with and without sudo, but perhaps the issue lies with my settings in the discord dev portal.

my dev portal settings for the bot:

scopes:
- bot
- applications.commands

bot permissions:
- send messages
- read message history
- use slash commands
- connect
- speak

for API token, i copied from the field to the right of the "ICON" button under the Bot tab, beneath the username # 4 digit suffix
