### ISSUE TITLE
Purge Command message not defined

### ISSUE THREAD

**Issue by P0rt3r74** [TannerGabriel/discord-bot#86]
Bot shuts down when purge is used with the number 0.

**To Reproduce**
1.  /purge num: 0

**Expected behavior**
Error message should be displayed

**Desktop (please complete the following information):**
 - OS: Windows 10
 - CPU architecture: 64 bit

**Dependency versions:**
 - Nodejs version: 16.9.1

**Additional context (optional)**
I changed message on line 16 in purge.js to interaction and now it works.

\commands\purge.js:16
      return message.reply('Please provide a number between 2 and 100 for the number of messages to delete');
      ^

ReferenceError: message is not defined
    at Object.execute (C:\Users\Thomas\discord-bot\commands\purge.js:16:7)
    at module.exports.<anonymous> (C:\Users\Thomas\discord-bot\index.js:83:15)
    at module.exports.emit (node:events:394:28)
    at InteractionCreateAction.handle (C:\Users\Thomas\discord-bot\node_modules\discord.js\src\client\actions\InteractionCreate.js:66:12)
    at Object.module.exports [as INTERACTION_CREATE] (C:\Users\Thomas\discord-bot\node_modules\discord.js\src\client\websocket\handlers\INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (C:\Users\Thomas\discord-bot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:345:31)
    at WebSocketShard.onPacket (C:\Users\Thomas\discord-bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:443:22)
    at WebSocketShard.onMessage (C:\Users\Thomas\discord-bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:300:10)
    at WebSocket.onMessage (C:\Users\Thomas\discord-bot\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (node:events:394:28)

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/TannerGabriel/discord-bot/issues?q=is%3Aissue)

**Comment by TannerGabriel** [comment]
Thank you for reporting this issue. I will take a look at it later this week. If you want, you could also fix it yourself and contribute it to the repo.

**Comment by TannerGabriel** [comment]
It should be fixed now.
